// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: server_rpc.proto

package pb_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	pb_chat "server/pb/pb_chat"
	pb_common "server/pb/pb_common"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqJoinChatGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group  pb_chat.ChatGroup         `protobuf:"varint,1,opt,name=Group,proto3,enum=chat.ChatGroup" json:"Group,omitempty"`
	Tag    string                    `protobuf:"bytes,2,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Player *pb_common.PlayerBaseInfo `protobuf:"bytes,3,opt,name=Player,proto3" json:"Player,omitempty"`
}

func (x *ReqJoinChatGroup) Reset() {
	*x = ReqJoinChatGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqJoinChatGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqJoinChatGroup) ProtoMessage() {}

func (x *ReqJoinChatGroup) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqJoinChatGroup.ProtoReflect.Descriptor instead.
func (*ReqJoinChatGroup) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *ReqJoinChatGroup) GetGroup() pb_chat.ChatGroup {
	if x != nil {
		return x.Group
	}
	return pb_chat.ChatGroup_World
}

func (x *ReqJoinChatGroup) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ReqJoinChatGroup) GetPlayer() *pb_common.PlayerBaseInfo {
	if x != nil {
		return x.Player
	}
	return nil
}

type RespJoinChatGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode pb_common.ErrorCode `protobuf:"varint,1,opt,name=ErrCode,proto3,enum=common.ErrorCode" json:"ErrCode,omitempty"`
}

func (x *RespJoinChatGroup) Reset() {
	*x = RespJoinChatGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespJoinChatGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespJoinChatGroup) ProtoMessage() {}

func (x *RespJoinChatGroup) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespJoinChatGroup.ProtoReflect.Descriptor instead.
func (*RespJoinChatGroup) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RespJoinChatGroup) GetErrCode() pb_common.ErrorCode {
	if x != nil {
		return x.ErrCode
	}
	return pb_common.ErrorCode_Default
}

type ReqLeaveChatGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group      pb_chat.ChatGroup `protobuf:"varint,1,opt,name=Group,proto3,enum=chat.ChatGroup" json:"Group,omitempty"`
	Tag        string            `protobuf:"bytes,2,opt,name=Tag,proto3" json:"Tag,omitempty"`
	PlayerGuid string            `protobuf:"bytes,3,opt,name=PlayerGuid,proto3" json:"PlayerGuid,omitempty"`
}

func (x *ReqLeaveChatGroup) Reset() {
	*x = ReqLeaveChatGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLeaveChatGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLeaveChatGroup) ProtoMessage() {}

func (x *ReqLeaveChatGroup) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLeaveChatGroup.ProtoReflect.Descriptor instead.
func (*ReqLeaveChatGroup) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *ReqLeaveChatGroup) GetGroup() pb_chat.ChatGroup {
	if x != nil {
		return x.Group
	}
	return pb_chat.ChatGroup_World
}

func (x *ReqLeaveChatGroup) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ReqLeaveChatGroup) GetPlayerGuid() string {
	if x != nil {
		return x.PlayerGuid
	}
	return ""
}

type RespLeaveChatGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode pb_common.ErrorCode `protobuf:"varint,1,opt,name=ErrCode,proto3,enum=common.ErrorCode" json:"ErrCode,omitempty"`
}

func (x *RespLeaveChatGroup) Reset() {
	*x = RespLeaveChatGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespLeaveChatGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespLeaveChatGroup) ProtoMessage() {}

func (x *RespLeaveChatGroup) ProtoReflect() protoreflect.Message {
	mi := &file_server_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespLeaveChatGroup.ProtoReflect.Descriptor instead.
func (*RespLeaveChatGroup) Descriptor() ([]byte, []int) {
	return file_server_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *RespLeaveChatGroup) GetErrCode() pb_common.ErrorCode {
	if x != nil {
		return x.ErrCode
	}
	return pb_common.ErrorCode_Default
}

var File_server_rpc_proto protoreflect.FileDescriptor

var file_server_rpc_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x1a, 0x0a, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x7b, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x74,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x25, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x10, 0x0a, 0x03,
	0x54, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x54, 0x61, 0x67, 0x12, 0x2e,
	0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x61,
	0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x40,
	0x0a, 0x11, 0x52, 0x65, 0x73, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x12, 0x2b, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x22, 0x6c, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x43, 0x68, 0x61, 0x74,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x25, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x10, 0x0a, 0x03,
	0x54, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x54, 0x61, 0x67, 0x12, 0x1e,
	0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x47, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x47, 0x75, 0x69, 0x64, 0x22, 0x41,
	0x0a, 0x12, 0x52, 0x65, 0x73, 0x70, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x43, 0x68, 0x61, 0x74, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x12, 0x2b, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x42, 0x12, 0x5a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x70,
	0x62, 0x5f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_rpc_proto_rawDescOnce sync.Once
	file_server_rpc_proto_rawDescData = file_server_rpc_proto_rawDesc
)

func file_server_rpc_proto_rawDescGZIP() []byte {
	file_server_rpc_proto_rawDescOnce.Do(func() {
		file_server_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_rpc_proto_rawDescData)
	})
	return file_server_rpc_proto_rawDescData
}

var file_server_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_server_rpc_proto_goTypes = []interface{}{
	(*ReqJoinChatGroup)(nil),         // 0: rpc.ReqJoinChatGroup
	(*RespJoinChatGroup)(nil),        // 1: rpc.RespJoinChatGroup
	(*ReqLeaveChatGroup)(nil),        // 2: rpc.ReqLeaveChatGroup
	(*RespLeaveChatGroup)(nil),       // 3: rpc.RespLeaveChatGroup
	(pb_chat.ChatGroup)(0),           // 4: chat.ChatGroup
	(*pb_common.PlayerBaseInfo)(nil), // 5: common.PlayerBaseInfo
	(pb_common.ErrorCode)(0),         // 6: common.ErrorCode
}
var file_server_rpc_proto_depIdxs = []int32{
	4, // 0: rpc.ReqJoinChatGroup.Group:type_name -> chat.ChatGroup
	5, // 1: rpc.ReqJoinChatGroup.Player:type_name -> common.PlayerBaseInfo
	6, // 2: rpc.RespJoinChatGroup.ErrCode:type_name -> common.ErrorCode
	4, // 3: rpc.ReqLeaveChatGroup.Group:type_name -> chat.ChatGroup
	6, // 4: rpc.RespLeaveChatGroup.ErrCode:type_name -> common.ErrorCode
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_server_rpc_proto_init() }
func file_server_rpc_proto_init() {
	if File_server_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqJoinChatGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespJoinChatGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqLeaveChatGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespLeaveChatGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_rpc_proto_goTypes,
		DependencyIndexes: file_server_rpc_proto_depIdxs,
		MessageInfos:      file_server_rpc_proto_msgTypes,
	}.Build()
	File_server_rpc_proto = out.File
	file_server_rpc_proto_rawDesc = nil
	file_server_rpc_proto_goTypes = nil
	file_server_rpc_proto_depIdxs = nil
}
