// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: http.proto

package pb_http

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	pb_common "server/pb/pb_common"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqEntry_EnumPlatform int32

const (
	ReqEntry_None    ReqEntry_EnumPlatform = 0
	ReqEntry_Android ReqEntry_EnumPlatform = 1
	ReqEntry_Ios     ReqEntry_EnumPlatform = 2
	ReqEntry_WinPC   ReqEntry_EnumPlatform = 3
)

// Enum value maps for ReqEntry_EnumPlatform.
var (
	ReqEntry_EnumPlatform_name = map[int32]string{
		0: "None",
		1: "Android",
		2: "Ios",
		3: "WinPC",
	}
	ReqEntry_EnumPlatform_value = map[string]int32{
		"None":    0,
		"Android": 1,
		"Ios":     2,
		"WinPC":   3,
	}
)

func (x ReqEntry_EnumPlatform) Enum() *ReqEntry_EnumPlatform {
	p := new(ReqEntry_EnumPlatform)
	*p = x
	return p
}

func (x ReqEntry_EnumPlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReqEntry_EnumPlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_http_proto_enumTypes[0].Descriptor()
}

func (ReqEntry_EnumPlatform) Type() protoreflect.EnumType {
	return &file_http_proto_enumTypes[0]
}

func (x ReqEntry_EnumPlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReqEntry_EnumPlatform.Descriptor instead.
func (ReqEntry_EnumPlatform) EnumDescriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{0, 0}
}

type ReqEntry_EnumEnv int32

const (
	ReqEntry_Dev    ReqEntry_EnumEnv = 0 //开发服
	ReqEntry_Alpha  ReqEntry_EnumEnv = 2 //内网测试服
	ReqEntry_Office ReqEntry_EnumEnv = 1 //正式服
)

// Enum value maps for ReqEntry_EnumEnv.
var (
	ReqEntry_EnumEnv_name = map[int32]string{
		0: "Dev",
		2: "Alpha",
		1: "Office",
	}
	ReqEntry_EnumEnv_value = map[string]int32{
		"Dev":    0,
		"Alpha":  2,
		"Office": 1,
	}
)

func (x ReqEntry_EnumEnv) Enum() *ReqEntry_EnumEnv {
	p := new(ReqEntry_EnumEnv)
	*p = x
	return p
}

func (x ReqEntry_EnumEnv) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReqEntry_EnumEnv) Descriptor() protoreflect.EnumDescriptor {
	return file_http_proto_enumTypes[1].Descriptor()
}

func (ReqEntry_EnumEnv) Type() protoreflect.EnumType {
	return &file_http_proto_enumTypes[1]
}

func (x ReqEntry_EnumEnv) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReqEntry_EnumEnv.Descriptor instead.
func (ReqEntry_EnumEnv) EnumDescriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{0, 1}
}

type ReqEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secret      string                `protobuf:"bytes,1,opt,name=Secret,proto3" json:"Secret,omitempty"`                                      //密钥
	UUID        string                `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`                                          //设备号
	Platform    ReqEntry_EnumPlatform `protobuf:"varint,3,opt,name=Platform,proto3,enum=http.ReqEntry_EnumPlatform" json:"Platform,omitempty"` //平台
	Env         ReqEntry_EnumEnv      `protobuf:"varint,4,opt,name=Env,proto3,enum=http.ReqEntry_EnumEnv" json:"Env,omitempty"`                //环境
	ResVersion  string                `protobuf:"bytes,5,opt,name=ResVersion,proto3" json:"ResVersion,omitempty"`                              //客户端资源版本号，用于判断热更新
	GameVersion string                `protobuf:"bytes,6,opt,name=GameVersion,proto3" json:"GameVersion,omitempty"`                            //游戏版本号，用于强更等内容
}

func (x *ReqEntry) Reset() {
	*x = ReqEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqEntry) ProtoMessage() {}

func (x *ReqEntry) ProtoReflect() protoreflect.Message {
	mi := &file_http_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqEntry.ProtoReflect.Descriptor instead.
func (*ReqEntry) Descriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{0}
}

func (x *ReqEntry) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *ReqEntry) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *ReqEntry) GetPlatform() ReqEntry_EnumPlatform {
	if x != nil {
		return x.Platform
	}
	return ReqEntry_None
}

func (x *ReqEntry) GetEnv() ReqEntry_EnumEnv {
	if x != nil {
		return x.Env
	}
	return ReqEntry_Dev
}

func (x *ReqEntry) GetResVersion() string {
	if x != nil {
		return x.ResVersion
	}
	return ""
}

func (x *ReqEntry) GetGameVersion() string {
	if x != nil {
		return x.GameVersion
	}
	return ""
}

//入口消息resp，服务端将登录、注册、长连接等地址下发
type RespEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode      pb_common.ErrorCode `protobuf:"varint,1,opt,name=ErrCode,proto3,enum=common.ErrorCode" json:"ErrCode,omitempty"`
	LoginUrl     string              `protobuf:"bytes,2,opt,name=LoginUrl,proto3" json:"LoginUrl,omitempty"`         //登录http地址
	RegisterUrl  string              `protobuf:"bytes,3,opt,name=RegisterUrl,proto3" json:"RegisterUrl,omitempty"`   //注册http地址
	TcpUrl       *RespEntry_Addr     `protobuf:"bytes,4,opt,name=TcpUrl,proto3" json:"TcpUrl,omitempty"`             // TCP连接地址
	WebSocketUrl *RespEntry_Addr     `protobuf:"bytes,5,opt,name=WebSocketUrl,proto3" json:"WebSocketUrl,omitempty"` // Websocket连接地址
}

func (x *RespEntry) Reset() {
	*x = RespEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespEntry) ProtoMessage() {}

func (x *RespEntry) ProtoReflect() protoreflect.Message {
	mi := &file_http_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespEntry.ProtoReflect.Descriptor instead.
func (*RespEntry) Descriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{1}
}

func (x *RespEntry) GetErrCode() pb_common.ErrorCode {
	if x != nil {
		return x.ErrCode
	}
	return pb_common.ErrorCode_Default
}

func (x *RespEntry) GetLoginUrl() string {
	if x != nil {
		return x.LoginUrl
	}
	return ""
}

func (x *RespEntry) GetRegisterUrl() string {
	if x != nil {
		return x.RegisterUrl
	}
	return ""
}

func (x *RespEntry) GetTcpUrl() *RespEntry_Addr {
	if x != nil {
		return x.TcpUrl
	}
	return nil
}

func (x *RespEntry) GetWebSocketUrl() *RespEntry_Addr {
	if x != nil {
		return x.WebSocketUrl
	}
	return nil
}

type ReqRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account   string `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Password  string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	AppId     string `protobuf:"bytes,3,opt,name=AppId,proto3" json:"AppId,omitempty"`         //appId
	ChannelId string `protobuf:"bytes,4,opt,name=ChannelId,proto3" json:"ChannelId,omitempty"` //渠道
	MacId     string `protobuf:"bytes,5,opt,name=MacId,proto3" json:"MacId,omitempty"`         //登录设备物理地址
}

func (x *ReqRegister) Reset() {
	*x = ReqRegister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqRegister) ProtoMessage() {}

func (x *ReqRegister) ProtoReflect() protoreflect.Message {
	mi := &file_http_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqRegister.ProtoReflect.Descriptor instead.
func (*ReqRegister) Descriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{2}
}

func (x *ReqRegister) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ReqRegister) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ReqRegister) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ReqRegister) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ReqRegister) GetMacId() string {
	if x != nil {
		return x.MacId
	}
	return ""
}

type RespRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode pb_common.ErrorCode `protobuf:"varint,1,opt,name=ErrCode,proto3,enum=common.ErrorCode" json:"ErrCode,omitempty"`
}

func (x *RespRegister) Reset() {
	*x = RespRegister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespRegister) ProtoMessage() {}

func (x *RespRegister) ProtoReflect() protoreflect.Message {
	mi := &file_http_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespRegister.ProtoReflect.Descriptor instead.
func (*RespRegister) Descriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{3}
}

func (x *RespRegister) GetErrCode() pb_common.ErrorCode {
	if x != nil {
		return x.ErrCode
	}
	return pb_common.ErrorCode_Default
}

type ReqLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account  string `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	AppId    string `protobuf:"bytes,3,opt,name=AppId,proto3" json:"AppId,omitempty"` //appId
}

func (x *ReqLogin) Reset() {
	*x = ReqLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLogin) ProtoMessage() {}

func (x *ReqLogin) ProtoReflect() protoreflect.Message {
	mi := &file_http_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLogin.ProtoReflect.Descriptor instead.
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{4}
}

func (x *ReqLogin) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ReqLogin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ReqLogin) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type RespLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode pb_common.ErrorCode `protobuf:"varint,1,opt,name=ErrCode,proto3,enum=common.ErrorCode" json:"ErrCode,omitempty"`
	Token   string              `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *RespLogin) Reset() {
	*x = RespLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespLogin) ProtoMessage() {}

func (x *RespLogin) ProtoReflect() protoreflect.Message {
	mi := &file_http_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespLogin.ProtoReflect.Descriptor instead.
func (*RespLogin) Descriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{5}
}

func (x *RespLogin) GetErrCode() pb_common.ErrorCode {
	if x != nil {
		return x.ErrCode
	}
	return pb_common.ErrorCode_Default
}

func (x *RespLogin) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RespEntry_Addr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=Host,proto3" json:"Host,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
}

func (x *RespEntry_Addr) Reset() {
	*x = RespEntry_Addr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_http_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespEntry_Addr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespEntry_Addr) ProtoMessage() {}

func (x *RespEntry_Addr) ProtoReflect() protoreflect.Message {
	mi := &file_http_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespEntry_Addr.ProtoReflect.Descriptor instead.
func (*RespEntry_Addr) Descriptor() ([]byte, []int) {
	return file_http_proto_rawDescGZIP(), []int{1, 0}
}

func (x *RespEntry_Addr) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RespEntry_Addr) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_http_proto protoreflect.FileDescriptor

var file_http_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x68, 0x74,
	0x74, 0x70, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xc1, 0x02, 0x0a, 0x08, 0x52, 0x65, 0x71, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x37, 0x0a, 0x08, 0x50, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x68, 0x74,
	0x74, 0x70, 0x2e, 0x52, 0x65, 0x71, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x45, 0x6e, 0x75, 0x6d,
	0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x12, 0x28, 0x0a, 0x03, 0x45, 0x6e, 0x76, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x16, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x52, 0x65, 0x71, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e,
	0x45, 0x6e, 0x75, 0x6d, 0x45, 0x6e, 0x76, 0x52, 0x03, 0x45, 0x6e, 0x76, 0x12, 0x1e, 0x0a, 0x0a,
	0x52, 0x65, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x52, 0x65, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b,
	0x47, 0x61, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x39,
	0x0a, 0x0c, 0x45, 0x6e, 0x75, 0x6d, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x08,
	0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x6e, 0x64, 0x72,
	0x6f, 0x69, 0x64, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x6f, 0x73, 0x10, 0x02, 0x12, 0x09,
	0x0a, 0x05, 0x57, 0x69, 0x6e, 0x50, 0x43, 0x10, 0x03, 0x22, 0x29, 0x0a, 0x07, 0x45, 0x6e, 0x75,
	0x6d, 0x45, 0x6e, 0x76, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x65, 0x76, 0x10, 0x00, 0x12, 0x09, 0x0a,
	0x05, 0x41, 0x6c, 0x70, 0x68, 0x61, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x69,
	0x63, 0x65, 0x10, 0x01, 0x22, 0x8e, 0x02, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x2b, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x2c, 0x0a,
	0x06, 0x54, 0x63, 0x70, 0x55, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x68, 0x74, 0x74, 0x70, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x41,
	0x64, 0x64, 0x72, 0x52, 0x06, 0x54, 0x63, 0x70, 0x55, 0x72, 0x6c, 0x12, 0x38, 0x0a, 0x0c, 0x57,
	0x65, 0x62, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x52, 0x0c, 0x57, 0x65, 0x62, 0x53, 0x6f, 0x63, 0x6b,
	0x65, 0x74, 0x55, 0x72, 0x6c, 0x1a, 0x2e, 0x0a, 0x04, 0x41, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x6f, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x8d, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x41,
	0x70, 0x70, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x41, 0x70, 0x70, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x4d, 0x61, 0x63, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x4d, 0x61, 0x63, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x22, 0x56, 0x0a, 0x08, 0x52, 0x65, 0x71, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x41, 0x70, 0x70, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x09, 0x52, 0x65,
	0x73, 0x70, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x2b, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x45, 0x72, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x13, 0x5a, 0x11, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x5f, 0x68, 0x74, 0x74, 0x70, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_http_proto_rawDescOnce sync.Once
	file_http_proto_rawDescData = file_http_proto_rawDesc
)

func file_http_proto_rawDescGZIP() []byte {
	file_http_proto_rawDescOnce.Do(func() {
		file_http_proto_rawDescData = protoimpl.X.CompressGZIP(file_http_proto_rawDescData)
	})
	return file_http_proto_rawDescData
}

var file_http_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_http_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_http_proto_goTypes = []interface{}{
	(ReqEntry_EnumPlatform)(0), // 0: http.ReqEntry.EnumPlatform
	(ReqEntry_EnumEnv)(0),      // 1: http.ReqEntry.EnumEnv
	(*ReqEntry)(nil),           // 2: http.ReqEntry
	(*RespEntry)(nil),          // 3: http.RespEntry
	(*ReqRegister)(nil),        // 4: http.ReqRegister
	(*RespRegister)(nil),       // 5: http.RespRegister
	(*ReqLogin)(nil),           // 6: http.ReqLogin
	(*RespLogin)(nil),          // 7: http.RespLogin
	(*RespEntry_Addr)(nil),     // 8: http.RespEntry.Addr
	(pb_common.ErrorCode)(0),   // 9: common.ErrorCode
}
var file_http_proto_depIdxs = []int32{
	0, // 0: http.ReqEntry.Platform:type_name -> http.ReqEntry.EnumPlatform
	1, // 1: http.ReqEntry.Env:type_name -> http.ReqEntry.EnumEnv
	9, // 2: http.RespEntry.ErrCode:type_name -> common.ErrorCode
	8, // 3: http.RespEntry.TcpUrl:type_name -> http.RespEntry.Addr
	8, // 4: http.RespEntry.WebSocketUrl:type_name -> http.RespEntry.Addr
	9, // 5: http.RespRegister.ErrCode:type_name -> common.ErrorCode
	9, // 6: http.RespLogin.ErrCode:type_name -> common.ErrorCode
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_http_proto_init() }
func file_http_proto_init() {
	if File_http_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_http_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqRegister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespRegister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_http_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespEntry_Addr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_http_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_http_proto_goTypes,
		DependencyIndexes: file_http_proto_depIdxs,
		EnumInfos:         file_http_proto_enumTypes,
		MessageInfos:      file_http_proto_msgTypes,
	}.Build()
	File_http_proto = out.File
	file_http_proto_rawDesc = nil
	file_http_proto_goTypes = nil
	file_http_proto_depIdxs = nil
}
