// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: lobby.proto

package pb_lobby

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	pb_common "server/pb/pb_common"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"` //登录返回的token，带上
}

func (x *ReqAuth) Reset() {
	*x = ReqAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqAuth) ProtoMessage() {}

func (x *ReqAuth) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqAuth.ProtoReflect.Descriptor instead.
func (*ReqAuth) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{0}
}

func (x *ReqAuth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RespAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode  pb_common.ErrorCode       `protobuf:"varint,1,opt,name=ErrCode,proto3,enum=common.ErrorCode" json:"ErrCode,omitempty"`
	BaseInfo *pb_common.PlayerBaseInfo `protobuf:"bytes,2,opt,name=BaseInfo,proto3" json:"BaseInfo,omitempty"` //玩家基础信息
}

func (x *RespAuth) Reset() {
	*x = RespAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespAuth) ProtoMessage() {}

func (x *RespAuth) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespAuth.ProtoReflect.Descriptor instead.
func (*RespAuth) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{1}
}

func (x *RespAuth) GetErrCode() pb_common.ErrorCode {
	if x != nil {
		return x.ErrCode
	}
	return pb_common.ErrorCode_Default
}

func (x *RespAuth) GetBaseInfo() *pb_common.PlayerBaseInfo {
	if x != nil {
		return x.BaseInfo
	}
	return nil
}

//获取大厅信息
type ReqLobbyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqLobbyInfo) Reset() {
	*x = ReqLobbyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLobbyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLobbyInfo) ProtoMessage() {}

func (x *ReqLobbyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLobbyInfo.ProtoReflect.Descriptor instead.
func (*ReqLobbyInfo) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{2}
}

type RespLobbyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*RespLobbyInfo_LobbyInfo `protobuf:"bytes,1,rep,name=Infos,proto3" json:"Infos,omitempty"`
}

func (x *RespLobbyInfo) Reset() {
	*x = RespLobbyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespLobbyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespLobbyInfo) ProtoMessage() {}

func (x *RespLobbyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespLobbyInfo.ProtoReflect.Descriptor instead.
func (*RespLobbyInfo) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{3}
}

func (x *RespLobbyInfo) GetInfos() []*RespLobbyInfo_LobbyInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

type ReqChangePlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NickName string           `protobuf:"bytes,1,opt,name=NickName,proto3" json:"NickName,omitempty"`
	Gender   pb_common.Gender `protobuf:"varint,2,opt,name=Gender,proto3,enum=common.Gender" json:"Gender,omitempty"`
	Avatar   string           `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
}

func (x *ReqChangePlayerInfo) Reset() {
	*x = ReqChangePlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqChangePlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqChangePlayerInfo) ProtoMessage() {}

func (x *ReqChangePlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqChangePlayerInfo.ProtoReflect.Descriptor instead.
func (*ReqChangePlayerInfo) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{4}
}

func (x *ReqChangePlayerInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *ReqChangePlayerInfo) GetGender() pb_common.Gender {
	if x != nil {
		return x.Gender
	}
	return pb_common.Gender_Unknow
}

func (x *ReqChangePlayerInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type RespChangePlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode pb_common.ErrorCode `protobuf:"varint,1,opt,name=ErrCode,proto3,enum=common.ErrorCode" json:"ErrCode,omitempty"`
}

func (x *RespChangePlayerInfo) Reset() {
	*x = RespChangePlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespChangePlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespChangePlayerInfo) ProtoMessage() {}

func (x *RespChangePlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespChangePlayerInfo.ProtoReflect.Descriptor instead.
func (*RespChangePlayerInfo) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{5}
}

func (x *RespChangePlayerInfo) GetErrCode() pb_common.ErrorCode {
	if x != nil {
		return x.ErrCode
	}
	return pb_common.ErrorCode_Default
}

type RespLobbyInfo_LobbyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId   uint32 `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId,omitempty"`    //游戏Id
	GameName string `protobuf:"bytes,2,opt,name=GameName,proto3" json:"GameName,omitempty"` //游戏名称
	IsOpen   bool   `protobuf:"varint,3,opt,name=IsOpen,proto3" json:"IsOpen,omitempty"`    //该游戏是否已开启
}

func (x *RespLobbyInfo_LobbyInfo) Reset() {
	*x = RespLobbyInfo_LobbyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lobby_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespLobbyInfo_LobbyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespLobbyInfo_LobbyInfo) ProtoMessage() {}

func (x *RespLobbyInfo_LobbyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lobby_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespLobbyInfo_LobbyInfo.ProtoReflect.Descriptor instead.
func (*RespLobbyInfo_LobbyInfo) Descriptor() ([]byte, []int) {
	return file_lobby_proto_rawDescGZIP(), []int{3, 0}
}

func (x *RespLobbyInfo_LobbyInfo) GetGameId() uint32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *RespLobbyInfo_LobbyInfo) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *RespLobbyInfo_LobbyInfo) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

var File_lobby_proto protoreflect.FileDescriptor

var file_lobby_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c,
	0x6f, 0x62, 0x62, 0x79, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x1f, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x41, 0x75, 0x74, 0x68, 0x12, 0x14, 0x0a,
	0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x6b, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x41, 0x75, 0x74, 0x68, 0x12,
	0x2b, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x32, 0x0a, 0x08,
	0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x61,
	0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x0e, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x9e, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x34, 0x0a, 0x05, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x4c, 0x6f,
	0x62, 0x62, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x05, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x1a, 0x57, 0x0a, 0x09, 0x4c, 0x6f, 0x62, 0x62,
	0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x73, 0x4f,
	0x70, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x49, 0x73, 0x4f, 0x70, 0x65,
	0x6e, 0x22, 0x71, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x52, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x22, 0x43, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x70, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2b, 0x0a, 0x07,
	0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x5f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lobby_proto_rawDescOnce sync.Once
	file_lobby_proto_rawDescData = file_lobby_proto_rawDesc
)

func file_lobby_proto_rawDescGZIP() []byte {
	file_lobby_proto_rawDescOnce.Do(func() {
		file_lobby_proto_rawDescData = protoimpl.X.CompressGZIP(file_lobby_proto_rawDescData)
	})
	return file_lobby_proto_rawDescData
}

var file_lobby_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_lobby_proto_goTypes = []interface{}{
	(*ReqAuth)(nil),                  // 0: lobby.ReqAuth
	(*RespAuth)(nil),                 // 1: lobby.RespAuth
	(*ReqLobbyInfo)(nil),             // 2: lobby.ReqLobbyInfo
	(*RespLobbyInfo)(nil),            // 3: lobby.RespLobbyInfo
	(*ReqChangePlayerInfo)(nil),      // 4: lobby.ReqChangePlayerInfo
	(*RespChangePlayerInfo)(nil),     // 5: lobby.RespChangePlayerInfo
	(*RespLobbyInfo_LobbyInfo)(nil),  // 6: lobby.RespLobbyInfo.LobbyInfo
	(pb_common.ErrorCode)(0),         // 7: common.ErrorCode
	(*pb_common.PlayerBaseInfo)(nil), // 8: common.PlayerBaseInfo
	(pb_common.Gender)(0),            // 9: common.Gender
}
var file_lobby_proto_depIdxs = []int32{
	7, // 0: lobby.RespAuth.ErrCode:type_name -> common.ErrorCode
	8, // 1: lobby.RespAuth.BaseInfo:type_name -> common.PlayerBaseInfo
	6, // 2: lobby.RespLobbyInfo.Infos:type_name -> lobby.RespLobbyInfo.LobbyInfo
	9, // 3: lobby.ReqChangePlayerInfo.Gender:type_name -> common.Gender
	7, // 4: lobby.RespChangePlayerInfo.ErrCode:type_name -> common.ErrorCode
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_lobby_proto_init() }
func file_lobby_proto_init() {
	if File_lobby_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lobby_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqLobbyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespLobbyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqChangePlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespChangePlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lobby_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespLobbyInfo_LobbyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lobby_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lobby_proto_goTypes,
		DependencyIndexes: file_lobby_proto_depIdxs,
		MessageInfos:      file_lobby_proto_msgTypes,
	}.Build()
	File_lobby_proto = out.File
	file_lobby_proto_rawDesc = nil
	file_lobby_proto_goTypes = nil
	file_lobby_proto_depIdxs = nil
}
